kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: runai-job-viewer
rules:
  - apiGroups: [ "" ]
    resources: [ "endpoints", "events", "namespaces", "configmaps", "pods", "nodes", "services", "services/proxy" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "apps" ]
    resources: [ "statefulsets", "replicasets", "deployments" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "discovery.k8s.io" ]
    resources: [ "endpointslices" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "batch" ]
    resources: [ "jobs" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "run.ai" ]
    resources: [ "runaijobs", "projects" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "extensions" ]
    resources: [ "ingresses" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "ingresses" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "schedueling" ]
    resources: [ "priorityclasses" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "kubeflow.org" ]
    resources: [ "mpijobs" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "route.openshift.io" ]
    resources: [ "routes" ]
    verbs: [ "get" ]

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: runai-job-executor
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps", "services", "persistentvolumeclaims", "pods/exec", "pods/attach", "pods/portforward" ]
    verbs: [ "create", "update", "patch", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "persistentvolumeclaims", "pods/log", "pods/exec", "pods/attach", "pods/portforward" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "apps" ]
    resources: [ "statefulsets", "replicasets", "deployments" ]
    verbs: [ "create", "update", "patch", "delete" ]
  - apiGroups: [ "extensions" ]
    resources: [ "ingresses" ]
    verbs: [ "create", "update", "patch", "delete" ]
  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "ingresses" ]
    verbs: [ "create", "update", "patch", "delete" ]
  - apiGroups: [ "batch" ]
    resources: [ "jobs" ]
    verbs: [ "create", "update", "patch", "delete" ]
  - apiGroups: [ "run.ai" ]
    resources: [ "runaijobs" ]
    verbs: [ "create", "update", "patch", "delete" ]
  - apiGroups: [ "kubeflow.org" ]
    resources: [ "mpijobs" ]
    verbs: [ "create", "update", "patch", "delete" ]
