apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: runai-cluster
    meta.helm.sh/release-namespace: runai
  labels:
    app.kubernetes.io/managed-by: Helm
  name: runai-job-executor
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  - persistentvolumeclaims
  - pods/exec
  - pods/attach
  - pods/portforward
  verbs:
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - pods/log
  - pods/exec
  - pods/attach
  - pods/portforward
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  - replicasets
  - deployments
  verbs:
  - create
  - update
  - patch
  - delete
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - update
  - patch
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - update
  - patch
  - delete
- apiGroups:
  - run.ai
  resources:
  - runaijobs
  - interactiveworkloads
  - trainingworkloads
  - deploymentworkloads
  verbs:
  - create
  - update
  - patch
  - delete
- apiGroups:
  - kubeflow.org
  resources:
  - mpijobs
  verbs:
  - create
  - update
  - patch
  - delete
